/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Cliente;
import Controller.Endereco;
import Model.Dao_Cliente;
import Model.Dao_Endereco;
import auxiliares.Validacao;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DESENVOLVIMENTO
 */
public class CadastroCliente extends javax.swing.JDialog {

    Font roboto = null;
    Font rodape = null;
    
    public CadastroCliente() {
        initComponents();
        
        try{
        roboto = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("fonts/Roboto-Regular.ttf"));
        }
        catch(IOException|FontFormatException e){
             System.out.println("Erro: " + e);
        }
        
        rodape = roboto.deriveFont(Font.PLAIN, 13);
        
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        
        ge.registerFont(rodape);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_CPF = new javax.swing.JFormattedTextField();
        txt_nascimento = new javax.swing.JFormattedTextField();
        btn_cadastro = new javax.swing.JLabel();
        txt_comp = new javax.swing.JTextField();
        form_Comp = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        form_Numero = new javax.swing.JLabel();
        txt_estado = new javax.swing.JTextField();
        form_Estado = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        form_Cidade = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        form_Bairro = new javax.swing.JLabel();
        txt_rua = new javax.swing.JTextField();
        form_Rua = new javax.swing.JLabel();
        form_CPF = new javax.swing.JLabel();
        form_Nascimento = new javax.swing.JLabel();
        txt_celular = new javax.swing.JFormattedTextField();
        form_Celular = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        form_Nome = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        form_Email = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hotel Plus Service - Cadastro");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_CPF.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_CPF.setBorder(null);
        txt_CPF.setForeground(new java.awt.Color(83, 83, 83));
        try {
            txt_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_CPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CPFKeyTyped(evt);
            }
        });
        getContentPane().add(txt_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 180, 30));

        txt_nascimento.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_nascimento.setBorder(null);
        txt_nascimento.setForeground(new java.awt.Color(83, 83, 83));
        try {
            txt_nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_nascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nascimentoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 180, 30));

        btn_cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_CadastroCliente_A.png"))); // NOI18N
        btn_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cadastroMouseExited(evt);
            }
        });
        getContentPane().add(btn_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 435, -1, -1));

        txt_comp.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_comp.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_comp.setForeground(new java.awt.Color(83, 83, 83));
        txt_comp.setBorder(null);
        txt_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_compActionPerformed(evt);
            }
        });
        txt_comp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_compKeyPressed(evt);
            }
        });
        getContentPane().add(txt_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 380, 190, 30));

        form_Comp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Comp_A.png"))); // NOI18N
        getContentPane().add(form_Comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        txt_numero.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_numero.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_numero.setForeground(new java.awt.Color(83, 83, 83));
        txt_numero.setBorder(null);
        txt_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numeroActionPerformed(evt);
            }
        });
        txt_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_numeroKeyPressed(evt);
            }
        });
        getContentPane().add(txt_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 380, 190, 30));

        form_Numero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Numero_A.png"))); // NOI18N
        getContentPane().add(form_Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        txt_estado.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_estado.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_estado.setForeground(new java.awt.Color(83, 83, 83));
        txt_estado.setBorder(null);
        txt_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estadoActionPerformed(evt);
            }
        });
        txt_estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_estadoKeyPressed(evt);
            }
        });
        getContentPane().add(txt_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 380, 180, 30));

        form_Estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Estado_A.png"))); // NOI18N
        getContentPane().add(form_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        txt_cidade.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_cidade.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_cidade.setForeground(new java.awt.Color(83, 83, 83));
        txt_cidade.setBorder(null);
        txt_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cidadeActionPerformed(evt);
            }
        });
        txt_cidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cidadeKeyPressed(evt);
            }
        });
        getContentPane().add(txt_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 320, 190, 30));

        form_Cidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Cidade_A.png"))); // NOI18N
        getContentPane().add(form_Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        txt_bairro.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_bairro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_bairro.setForeground(new java.awt.Color(83, 83, 83));
        txt_bairro.setBorder(null);
        txt_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bairroActionPerformed(evt);
            }
        });
        txt_bairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_bairroKeyPressed(evt);
            }
        });
        getContentPane().add(txt_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 320, 190, 30));

        form_Bairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Bairro_A.png"))); // NOI18N
        getContentPane().add(form_Bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        txt_rua.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_rua.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_rua.setForeground(new java.awt.Color(83, 83, 83));
        txt_rua.setBorder(null);
        txt_rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ruaActionPerformed(evt);
            }
        });
        txt_rua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ruaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 320, 190, 30));

        form_Rua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Rua_A.png"))); // NOI18N
        getContentPane().add(form_Rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        form_CPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_CPF_B.png"))); // NOI18N
        getContentPane().add(form_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        form_Nascimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Nasc_B.png"))); // NOI18N
        getContentPane().add(form_Nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        txt_celular.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_celular.setBorder(null);
        txt_celular.setForeground(new java.awt.Color(83, 83, 83));
        try {
            txt_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 160, 180, 30));

        form_Celular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Cel_B.png"))); // NOI18N
        getContentPane().add(form_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        txt_nome.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_nome.setForeground(new java.awt.Color(83, 83, 83));
        txt_nome.setBorder(null);
        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });
        txt_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomeKeyPressed(evt);
            }
        });
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 160, 180, 30));

        form_Nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Nome_A.png"))); // NOI18N
        getContentPane().add(form_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        txt_email.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_email.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_email.setForeground(new java.awt.Color(83, 83, 83));
        txt_email.setBorder(null);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 160, 180, 30));

        form_Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_Email_A.png"))); // NOI18N
        getContentPane().add(form_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BG_CadastroCliente.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_Email_B.png"));
        form_Email.setIcon( ii );
    }//GEN-LAST:event_txt_emailKeyPressed

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeKeyPressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_Nome_B.png"));
        form_Nome.setIcon( ii );
    }//GEN-LAST:event_txt_nomeKeyPressed

    private void txt_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_compActionPerformed

    private void txt_compKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_compKeyPressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_Comp_B.png"));
        form_Comp.setIcon( ii );
    }//GEN-LAST:event_txt_compKeyPressed

    private void txt_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numeroActionPerformed

    private void txt_numeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroKeyPressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_Numero_B.png"));
        form_Numero.setIcon( ii );
    }//GEN-LAST:event_txt_numeroKeyPressed

    private void txt_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estadoActionPerformed

    private void txt_estadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_estadoKeyPressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_Estado_B.png"));
        form_Estado.setIcon( ii );
    }//GEN-LAST:event_txt_estadoKeyPressed

    private void txt_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cidadeActionPerformed

    private void txt_cidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cidadeKeyPressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_Cidade_B.png"));
        form_Cidade.setIcon( ii );
    }//GEN-LAST:event_txt_cidadeKeyPressed

    private void txt_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bairroActionPerformed

    private void txt_bairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bairroKeyPressed
       ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_Bairro_B.png"));
       form_Bairro.setIcon( ii );
    }//GEN-LAST:event_txt_bairroKeyPressed

    private void txt_ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ruaActionPerformed

    private void txt_ruaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ruaKeyPressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_Rua_B.png"));
        form_Rua.setIcon( ii );
    }//GEN-LAST:event_txt_ruaKeyPressed

    private void btn_cadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastroMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/btn_CadastroCliente_B.png"));
        btn_cadastro.setIcon( ii );
    }//GEN-LAST:event_btn_cadastroMouseEntered

    private void btn_cadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastroMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/btn_CadastroCliente_A.png"));
        btn_cadastro.setIcon( ii );
    }//GEN-LAST:event_btn_cadastroMouseExited

    private void btn_cadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastroMouseClicked
        Object[] options = { "Confirmar", "Cancelar" };
        int opcao = JOptionPane.showOptionDialog(null, "Deseja prosseguir com o cadastro?","Confirmação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        
        if(opcao == 0){
            String campos[] = {txt_rua.getText(), txt_bairro.getText(), txt_numero.getText(), txt_comp.getText(), txt_cidade.getText(), txt_estado.getText(), txt_nome.getText(), txt_email.getText(), txt_celular.getText(), txt_nascimento.getText(), txt_CPF.getText()};
            
            if(Validacao.verificarCamposVazios(campos)){
                Cliente cadUser = new Cliente();
                Endereco cadEnd = new Endereco();
                cadEnd.inserirDados(txt_rua.getText(), txt_bairro.getText(), txt_numero.getText(), txt_comp.getText(), txt_cidade.getText(), txt_estado.getText());
                try {
                    cadUser.inserirDadosCliente(txt_nome.getText(), txt_email.getText(), txt_celular.getText(), txt_nascimento.getText(), txt_CPF.getText(), cadEnd);
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Houve um erro, contate o adminstrador do sistema");
                    Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                Dao_Endereco end = new Dao_Endereco();
                if(end.Salvar(cadEnd)){
                    Dao_Cliente user = new Dao_Cliente();
                    if(user.Salvar(cadUser, end.IDInsercao)){
                        JOptionPane.showMessageDialog(null, "Cliente Cadastrado!");
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Ocorreu um erro, Contate o Administrador");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro, Contate o Administrador");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Campos Vazios ou Email já Existente!");
            }
        }
    }//GEN-LAST:event_btn_cadastroMouseClicked

    private void txt_nascimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nascimentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nascimentoKeyTyped

    private void txt_CPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CPFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CPFKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cadastro;
    private javax.swing.JLabel form_Bairro;
    private javax.swing.JLabel form_CPF;
    private javax.swing.JLabel form_Celular;
    private javax.swing.JLabel form_Cidade;
    private javax.swing.JLabel form_Comp;
    private javax.swing.JLabel form_Email;
    private javax.swing.JLabel form_Estado;
    private javax.swing.JLabel form_Nascimento;
    private javax.swing.JLabel form_Nome;
    private javax.swing.JLabel form_Numero;
    private javax.swing.JLabel form_Rua;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField txt_CPF;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JFormattedTextField txt_celular;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_comp;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JFormattedTextField txt_nascimento;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_rua;
    // End of variables declaration//GEN-END:variables
}
