/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Usuario;
import Model.Dao_Usuario;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DESENVOLVIMENTO
 */
public class Login extends javax.swing.JFrame {

    Font roboto = null;
    Font rodape = null;
    
    public Login() {
        initComponents();
        
        try{
        roboto = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("fonts/Roboto-Regular.ttf"));
        }
        catch(IOException|FontFormatException e){
             System.out.println("Erro: " + e);
        }
        
        rodape = roboto.deriveFont(Font.PLAIN, 13);
        
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        
        ge.registerFont(rodape);  
        jLabel_Rodape1.setFont(rodape); 
        jLabel_Rodape2.setFont(rodape); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_password = new javax.swing.JPasswordField();
        form_password = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        form_user = new javax.swing.JLabel();
        jLabel_btn_cadastro = new javax.swing.JLabel();
        jLabel_btn_login = new javax.swing.JLabel();
        jLabel_Rodape2 = new javax.swing.JLabel();
        jLabel_Rodape1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Plus Service - Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_password.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_password.setBorder(null);
        txt_password.setOpaque(false);
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 248, 250, 30));

        form_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_password_A.png"))); // NOI18N
        getContentPane().add(form_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 220, -1, -1));

        txt_login.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_login.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_login.setForeground(new java.awt.Color(83, 83, 83));
        txt_login.setBorder(null);
        txt_login.setOpaque(false);
        txt_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_loginKeyPressed(evt);
            }
        });
        getContentPane().add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 168, 280, 30));

        form_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/form_user_A.png"))); // NOI18N
        getContentPane().add(form_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 140, -1, -1));

        jLabel_btn_cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_cadastro_A.png"))); // NOI18N
        jLabel_btn_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_btn_cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_btn_cadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_cadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_cadastroMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_btn_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 362, -1, -1));

        jLabel_btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_login_A.png"))); // NOI18N
        jLabel_btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_btn_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_btn_loginMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 300, -1, -1));

        jLabel_Rodape2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Rodape2.setText("de Análise e Desenvolvimento de Sistemas peos Discentes Caio Alexandre de Sousa Ramos e Lucas Eduardo Sampaio Andrade.");
        getContentPane().add(jLabel_Rodape2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 560, -1, -1));

        jLabel_Rodape1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Rodape1.setText("Este software é um protótipo desenvolvido durante uma avaliação da disciplina de Linguagem de Programação II no curso Tecnológico");
        getContentPane().add(jLabel_Rodape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 545, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login_form.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BG_login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_loginMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/btn_login_B.png"));
        jLabel_btn_login.setIcon( ii );
    }//GEN-LAST:event_jLabel_btn_loginMouseEntered

    private void jLabel_btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_loginMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/btn_login_A.png"));
        jLabel_btn_login.setIcon( ii );
    }//GEN-LAST:event_jLabel_btn_loginMouseExited

    private void jLabel_btn_cadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_cadastroMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/btn_cadastro_B.png"));
        jLabel_btn_cadastro.setIcon( ii );
    }//GEN-LAST:event_jLabel_btn_cadastroMouseEntered

    private void jLabel_btn_cadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_cadastroMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/btn_cadastro_A.png"));
        jLabel_btn_cadastro.setIcon( ii );
    }//GEN-LAST:event_jLabel_btn_cadastroMouseExited

    private void txt_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_loginKeyPressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_user_B.png"));
        form_user.setIcon( ii );
    }//GEN-LAST:event_txt_loginKeyPressed

    private void jLabel_btn_cadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_cadastroMouseClicked
        Cadastro cad = new Cadastro();
        cad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_btn_cadastroMouseClicked

    private void jLabel_btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_btn_loginMouseClicked
        Dao_Usuario login = new Dao_Usuario();
        List<Usuario> listar = login.buscarUnicaEmail(txt_login.getText());
        
        if(listar.isEmpty()){
            JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorretos");
        }else{
            Usuario user = listar.get(0);
            if(user.getSenha().equals("")){
                JOptionPane.showMessageDialog(null, "Usuário em análise, contate o administrador do sistema");
            }else if(txt_password.getText().equals(user.getSenha())){
                Object[] options = { "Confirmar", "Cancelar" };
                int opcao = JOptionPane.showOptionDialog(null, "Você está entrando como: \n" + user.getNome() + "\nDeseja prosseguir?","Confirmação", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
                if(opcao == 0){
                    new TelaInicial(user).setVisible(true);
                    this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorretos");
            }
        }
    }//GEN-LAST:event_jLabel_btn_loginMouseClicked

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/assets/form_password_B.png"));
        form_password.setIcon( ii );
    }//GEN-LAST:event_txt_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel form_password;
    private javax.swing.JLabel form_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Rodape1;
    private javax.swing.JLabel jLabel_Rodape2;
    private javax.swing.JLabel jLabel_btn_cadastro;
    private javax.swing.JLabel jLabel_btn_login;
    private javax.swing.JTextField txt_login;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
